---
- hosts: webb
  tasks:
          - name: Se till att senaste versionen av Apache är installerat 
            yum:
                    name: httpd
                    state: latest
          - name: Starta Apache vid boot.
            service:
                    name: httpd
                    enabled: yes
                    state: started
          - name: Definiera en vhost
            copy: 
                src: "filer/min_vhost.conf"
                dest: "/etc/httpd/conf.d/min_vhost.conf"
          - name: Restart Apache
            service:
                    name: httpd
                    state: restarted
